@startuml spriteRenderer

class Sprite {
  - src
  - xPos
  - yPos
  - loaded
  - width // Not implemented yet
  - height // Not implemented yet

  + Sprite(src, xPos, yPos)
  - createImage()
  - setSrc() // setImageSource ??
  + setPosition(xPos, yPos)
  + move(xPos, yPos) // Not implemented yet
  + get positionX()
  - set positionX(xPos)
  + get positionY()
  - set positionY(yPos)
  + get image()
  + waitForLoad()

}

class SpriteRenderer {
  - canvas
  - context
  - sprites
  
  + SpriteRenderer(canvas)
  - setContext()
  + add(sprite)
  + remove(sprite)
  - clear()
  + render()
}


@enduml